services:
  - type: web
    name: n8n-ffmpeg
    env: docker
    plan: starter
    autoDeploy: true
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8n-db
          property: port
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-db
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: N8N_HOST
        value: n8n-ffmpeg.onrender.com
      - key: N8N_PORT
        value: "443"
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://n8n-ffmpeg.onrender.com
      - key: GENERIC_TIMEZONE
        value: UTC
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"

databases:
  - name: n8n-db
    plan: starter
